# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
- job: StartVM
  pool: server
  steps:
  - task: AzureFunction@1
    inputs:
      function: 'https://tkssqlitogglevm.azurewebsites.net/api/HttpTrigger1'
      key: $(azureFunctionKey)
      method: 'POST'
      body: |
        {
            "action": "start",
            "vmname": "BuildAgentVM",
            "resourcegroup": "DevOps"
        }
      waitForCompletion: 'false'

- job: Build
  pool: MyAgentOnVM
  variables:
    buildConfiguration: 'Release'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

- job: StopVM
  pool: server
  dependsOn: Build
  steps:
  - task: AzureFunction@1
    inputs:
      function: 'https://tkssqlitogglevm.azurewebsites.net/api/HttpTrigger1'
      key: $(azureFunctionKey)
      method: 'POST'
      body: |
        {
            "action": "stop",
            "vmname": "BuildAgentVM",
            "resourcegroup": "DevOps"
        }
      waitForCompletion: 'false'