# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
- job: Build

  pool:
    name: TryDevOps
    demands: Agent.Name -equals aci-custom-linux-agent
    #vmImage: 'ubuntu-16.04'
    
  #container: mcr.microsoft.com/dotnet/core/sdk:2.2

  variables:
    buildConfiguration: 'Release'

  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
